import React from 'react'

const SalesTable: React.FC = () => {
	return (
		<div className="sales-form__container">
			<div className="sales-form__header center">
				<h3>Overal Sale Results</h3>
			</div>
			<div className="sales-form__content full">
				<div className="table-responsive">
					<table className='table-usual'>
						<thead>
							<tr>
								<th></th>
								<th>Vechicle Type</th>
								<th>Off</th>
								<th>Sld</th>
								<th>Rmn</th>
								<th>Sr</th>
								<th>MMR/RCVRY</th>
								<th>AVG/MLG</th>
								<th>BB/RCV</th>
								<th>RIMS/RCV</th>
								<th>FF/FF</th>
								<th>FF/FF</th>
								<th>FF/FF</th>
							</tr>
						</thead>
            <tbody>
              <tr>
                <th>GM</th>
                <td></td>
                <td>2</td>
                <td>0</td>
                <td>100.0</td>
                <td>96.4</td>
                <td>10853</td>
                <td>98.5</td>
                <td>100.9</td>
                <td>100.9</td>
                <td>100.9</td>
                <td>100.9</td>
                <td>100.9</td>
              </tr>
              <tr>
                <th>GMF</th>
                <td></td>
                <td>2</td>
                <td>0</td>
                <td>100.0</td>
                <td>96.4</td>
                <td>10853</td>
                <td>98.5</td>
                <td>100.9</td>
                <td>100.9</td>
                <td>100.9</td>
                <td>100.9</td>
                <td>100.9</td>
              </tr>
              <tr>
                <th>LEASE</th>
                <td>2</td>
                <td>2</td>
                <td>0</td>
                <td>100.0</td>
                <td>96.4</td>
                <td>10853</td>
                <td>98.5</td>
                <td>100.9</td>
                <td>100.9</td>
                <td>100.9</td>
                <td>100.9</td>
                <td>100.9</td>
              </tr>
              <tr>
                <th>REPO</th>
                <td>2</td>
                <td>2</td>
                <td>0</td>
                <td>100.0</td>
                <td>96.4</td>
                <td>10853</td>
                <td>98.5</td>
                <td>100.9</td>
                <td>100.9</td>
                <td>100.9</td>
                <td>100.9</td>
                <td>100.9</td>
              </tr>
              <tr>
                <th>GM</th>
                <td>2</td>
                <td>2</td>
                <td>0</td>
                <td>100.0</td>
                <td>96.4</td>
                <td>10853</td>
                <td>98.5</td>
                <td>100.9</td>
                <td>100.9</td>
                <td>100.9</td>
                <td>100.9</td>
                <td>100.9</td>
              </tr>
              <tr>
                <th>GM</th>
                <td>2</td>
                <td>2</td>
                <td>0</td>
                <td>100.0</td>
                <td>96.4</td>
                <td>10853</td>
                <td>98.5</td>
                <td>100.9</td>
                <td>100.9</td>
                <td>100.9</td>
                <td>100.9</td>
                <td>100.9</td>
              </tr>
              <tr>
                <th>GM</th>
                <td>2</td>
                <td>2</td>
                <td>0</td>
                <td>100.0</td>
                <td>96.4</td>
                <td>10853</td>
                <td>98.5</td>
                <td>100.9</td>
                <td>100.9</td>
                <td>100.9</td>
                <td>100.9</td>
                <td>100.9</td>
              </tr>
              <tr>
                <th>GM</th>
                <td>2</td>
                <td>2</td>
                <td>0</td>
                <td>100.0</td>
                <td>96.4</td>
                <td>10853</td>
                <td>98.5</td>
                <td>100.9</td>
                <td>100.9</td>
                <td>100.9</td>
                <td>100.9</td>
                <td>100.9</td>
              </tr>
              <tr>
                <th>GM</th>
                <td>2</td>
                <td>2</td>
                <td>0</td>
                <td>100.0</td>
                <td>96.4</td>
                <td>10853</td>
                <td>98.5</td>
                <td>100.9</td>
                <td>100.9</td>
                <td>100.9</td>
                <td>100.9</td>
                <td>100.9</td>
              </tr>
              <tr>
                <th>GM</th>
                <td>2</td>
                <td>2</td>
                <td>0</td>
                <td>100.0</td>
                <td>96.4</td>
                <td>10853</td>
                <td>98.5</td>
                <td>100.9</td>
                <td>100.9</td>
                <td>100.9</td>
                <td>100.9</td>
                <td>100.9</td>
              </tr>
              <tr>
                <th>TOTAL</th>
                <td>2</td>
                <td>2</td>
                <td>0</td>
                <td>100.0</td>
                <td>96.4</td>
                <td>10853</td>
                <td>98.5</td>
                <td>100.9</td>
                <td>100.9</td>
                <td>100.9</td>
                <td>100.9</td>
                <td>100.9</td>
              </tr>
            </tbody>
					</table>
				</div>
			</div>
		</div>
	)
}

export default SalesTable
